theme = "gocymru"

title = "Golang Cymru"

[blackfriday]
  extensions = ["hardLineBreak"]

[params]
  bio = "Welcome to the _golang.cymru_ homepage! We are an informal, friendly group of [Go programming language](https://golang.org/) enthusiasts based in Wales UK.\nThe group was set up so there could be a Go 1.6 launch party a little closer to home than the nearest which seemed to be London. We didn't get there but we now have our first welsh go meetup at cardiff.\nGet in touch if you are interested in setting up any other meetup groups anywhere else in the country"
  logo = "gopher-dragon.svg"
  copyright = "&copy; 2019 Golang Cymru\n\nWelsh Dragon Gopher curtesy of [Ashley McNamara](https://github.com/ashleymcnamara/gophers) used with kind permission"

  [[params.social]]
      name = "Github"
      icon = "fab fa-github"
      weight = 1
      url = "https://github.com/golang-cymru/"
  [[params.social]]
      name = "Meetup"
      icon = "fab fa-meetup"
      weight = 2
      url = "https://www.meetup.com/Cardiff-Go-Meetup/"
  [[params.social]]
      name = "Twitter"
      icon = "fab fa-twitter"
      weight = 3
      url = "https://twitter.com/cdfgolang/"
  [[params.social]]
      name = "Slack"
      icon = "fab fa-slack"
      weight = 4
      url = "https://gophers.slack.com/messages/cymru"

  [[params.hacks]]
      name = "Simple API"
      url = "https://github.com/golang-cymru/cardiff-meetup-code/tree/master/2016-11-simple-api"
      weight = 1
  [[params.hacks]]
      name = "LCD Digits"
      url = "https://github.com/golang-cymru/cardiff-meetup-code/tree/master/2017-01-tdd-lcd-digits"
      weight = 1
  [[params.hacks]]
      name = "GRPC"
      url = "https://github.com/golang-cymru/cardiff-meetup-code/tree/master/2017-07-grpc"
      weight = 1

  [[params.projects]]
      name = "Go Who"
      url = "https://github.com/golang-cymru/cardiff-meetup-code/tree/master/2019-03-07-go-who-proto"
      weight = 1

